name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arango-image: ["arangodb:3.6.8", "arangodb:3.7.3", "arangodb/enterprise:3.7.3"]

    steps:
    - uses: actions/checkout@v2
    
    - name: ArangoDB ${{ matrix.arango-image }}
      run: docker run -d --rm -e ARANGO_ROOT_PASSWORD= -p 8529:8529 -e ARANGO_LICENSE_KEY=${{ secrets.ARANGO_ENTERPRISE }} ${{ matrix.arango-image }}
    
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
    
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release
