name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: ArangoDB 3.6.4
      run: docker run -d --rm -e ARANGO_ROOT_PASSWORD= -p 8529:8529 arangodb:3.6.4
    
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "<Version>.*</Version>"
        replace: "<Version>${GITHUB_REF#refs/*/}</Version>"
        include: ".*\.csroj"
    
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release
